### ISSUE TITLE
单次消息输入字数限制

### ISSUE THREAD

**Issue by Pony-John** [smallnew666/ChatGPT-wxapp#2]
![Screenshot_20230308_160907_com.tencent.mm.jpg](https://user-images.githubusercontent.com/124037897/223657153-b23c5190-4e21-49b3-a04a-a36e49cfa5ed.jpg)

目前单次请求消息最多为140个汉字，这对于部分需求(给出一段论文让AI写总结、给出一段故事让AI续写等)字数不够用，希望能解决此字数限制。

**Comment by smallnew666** [comment]
这是input标签的字数限制 可以改用textarea
